### PR TITLE
fix(github): scm email is now correctly taken from github/gogs claims

### LINKED ISSUE #32: Retrieve email for Git Author from GitHub
Forge Generator seems to be relying on the Email in KeyCloak Token when setting up the Git Commit Author. This Email is the KC account email and might not be the same as GitHub knows. The end result is it might seem like 'someone else' is making the commit than the authorized user as there is no real link between authorization and git author on Github.

Forge Generator should call api.github.com/user and use the 'email' provided there, and if noone is set(no public email set), call api.github.com/api/user/email and use the primary one. 

Related https://github.com/openshiftio/openshift.io/issues/399

### PR DESCRIPTION
**Pull request by corinnekrych**
Fixes https://github.com/fabric8io/fabric8-generator/issues/32

see before fix: https://github.com/corinnekrych/august22bisbis
after fix: https://github.com/corinnekrych/august22bister

### CODE REVIEW

**Comment by aslakknutsen** [comment]
I've only quickly browsed the code, but it looks like it only takes 'public email' into account: https://github.com/fabric8io/fabric8-generator/blob/d9e0541b5589436793f8d06ee0517e39e87a7597/src/main/java/io/fabric8/forge/generator/github/GitHubFacade.java#L208

The OAuth claim:email allow you to read private email as well.

**Comment by aslakknutsen** [comment]
Then again, @corinnekrych doesn't seem to have a public email so I guess it gets it from somewhere.. :)

**Review by aslakknutsen — APPROVED** [review]
The end result looks good to me. Codewise I have no idea :)

**Comment by jstrachan** [comment]
@aslakknutsen for private emails this PR fixes it right? https://github.com/fabric8io/fabric8-generator/pull/50

**Review by jstrachan — COMMENTED** [review]
LGTM

**Comment by corinnekrych** [comment]
@jstrachan @aslakknutsen the only left issue if when gh user have disable public email AND block commit that publishes email. in that case the wizard is successful silently :(
see https://github.com/fabric8io/fabric8-generator/issues/31#issuecomment-324316864
this one should be fixed in a different repo.

**Comment by aslakknutsen** [comment]
@jstrachan maybe? :)

**Pull request merged**
